### ISSUE TITLE
请问没有exe怎么在windows运行？

### ISSUE THREAD

**Issue by DinorHow** [XIVN1987/DRTTView#1]
搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。

**Comment by XIVN1987** [comment]
我在两个论坛上发布了打包成的exe文件，你可以去其中之一下载：


阿莫电子：https://www.amobbs.com/thread-5708770-1-1.html?_dsign=f8282f57
21IC：http://bbs.21ic.com/icview-2643702-1-1.html


我还在这两个论坛上发不过多个其他工具的exe打包，，比如HFView、SVDView、RTTView对单片机调试还是非常有用的，，感兴趣可以下载试试




------------------ 原始邮件 ------------------
发件人: "DINOR"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 下午2:25
收件人: "XIVN1987/DRTTView"<DRTTView@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [XIVN1987/DRTTView] 请问没有exe怎么在windows运行？ (#1)




搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。

**Comment by DinorHow** [comment]
> 我在两个论坛上发布了打包成的exe文件，你可以去其中之一下载： 阿莫电子：https://www.amobbs.com/thread-5708770-1-1.html?_dsign=f8282f57 21IC：http://bbs.21ic.com/icview-2643702-1-1.html 我还在这两个论坛上发不过多个其他工具的exe打包，，比如HFView、SVDView、RTTView对单片机调试还是非常有用的，，感兴趣可以下载试试
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "DINOR"<notifications@github.com>; 发送时间: 2019年4月23日(星期二) 下午2:25 收件人: "XIVN1987/DRTTView"<DRTTView@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [XIVN1987/DRTTView] 请问没有exe怎么在windows运行？ (#1) 搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

非常感谢！

**Comment by XIVN1987** [comment]
> 搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。

我把exe上传到github上了，发布了个release，方便下载：https://github.com/XIVN1987/DRTTView/releases

**Comment by DinorHow** [comment]
> > 搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。
> 
> 我把exe上传到github上了，发布了个release，方便下载：https://github.com/XIVN1987/DRTTView/releases

太棒了！

**Comment by XIVN1987** [comment]
> > > 搞电子的实在是不懂这些，如果有exe直接点开运行最方便了。
> > 
> > 
> > 我把exe上传到github上了，发布了个release，方便下载：https://github.com/XIVN1987/DRTTView/releases
> 
> 太棒了！

刚才上传的可能不是最新代码打包而成的，，我用最新代码重新打包了一下更新到了release中，你可以下载试下
